apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostPID: true
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:v1.3.1
        ports:
        - containerPort: 9100
        volumeMounts:
        - name: rootfs
          mountPath: /host/root
          readOnly: true
      volumes:
      - name: rootfs
        hostPath:
          path: /

